version: '2'

services:
  uchain-explorer:
    build: .
    restart: always
    image: uchain-explorer:1.1.0
    container_name: uchain-explorer
    volumes:
      - ./data:/uchain-explorer/data
    ports:
      - "3000:3000"
